version: '3'
services:
  web:
    build: ./web
    ports:
      - 80:80
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase_${ENVIRONMENT}

  worker:
    build: ./worker
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    depends_on:
      - db